### ISSUE TITLE
Add `traceResolution: true` to tsconfig?

### ISSUE THREAD

**Issue by minato-ellie** [LinusBorg/vue-lib-template#6]
I'm a frontend newbie transitioning from backend development. Thank you so much for sharing this template. It's been incredibly helpful!

While working with it, my IDE struggled to resolve dependencies within the workspace, even though the code compiled and ran flawlessly. My IDE flagged errors with `TS2307: Cannot find module`. 
After some research and referring to this [TypeScript documentation page](https://www.typescriptlang.org/docs/handbook/module-resolution.html#tracing-module-resolution), I added "traceResolution": "true" to tsconfig.json and it resolved the issue for me.

Can I create a PR to solve this?

**Comment by LinusBorg** [comment]
In my understanding, this flag only adds debug output, I don't see how it could be necessary to make this work.
